# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 14:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20180221_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9 ]*$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9 ]*$')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only alphanumeric characters are allowed.', regex='^[a-zA-Z0-9 ]*$')]),
        ),
    ]
